In [50]:
from setup_data_structure import *
from regev_encryption_schemised import *
import json
import hashlib
import numpy as np
from toy_pir import *

In [51]:
# SCT logger/server sets up the data structure

file_path = "Example_SCTs.json"

# Read the JSON data from the file
with open(file_path, 'r') as file:
    sct_list = json.load(file)

# Output the loaded data to verify
print(len(sct_list))
print(type(sct_list[0]))
print(sct_list[0])

data_structure_for_sct = setup_a_function_bloom_filter(sct_list, 5)

# print(data_structure_for_sct)
# print(type(data_structure_for_sct))

print(data_structure_for_sct["a_function_bloom_filter"])
print(data_structure_for_sct["salt_list"])


3
<class 'dict'>
{'sct_version': 1, 'log_id': 'VWhJdXZrS0pIUFFrUk5ER2JDaWU=', 'timestamp': 1652934758000, 'extensions': '', 'signature': 'MEUCIQDqZIjuNXmV+Rm9dl7h4/u+vZG3+Yj5CISgAzimuths/aiEQIgNupUwGiW8QHfy7WqIuYGCuR+cPkryBJcRqRHTLFa4='}
[[0 1 0 0 1]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [1 0 1 1 0]]
[b'salt0', b'salt1', b'salt2', b'salt3', b'salt4']


In [52]:
rand_row = 3 # the randomly chosen row, publically shown to the auditoe

print(f"Client: I want to privately read an index i(which only I know) of row:{rand_row}")

Client: I want to privately an index i(which only I know) of row:3


In [58]:
print(f"Auditor: cool")

db = data_structure_for_sct["a_function_bloom_filter"][rand_row]


Auditor: cool


In [59]:
# client


bloom_filter_size = 5
sct_to_check = sct_list[2]


# i want to check if sct_list[2] is in the data structure
# get the third salt from the auditor
ith_salt = data_structure_for_sct["salt_list"][rand_row]

print(sct_to_check)

sct_i_hashed = serialise_and_hash(ith_salt, sct_to_check)
index_in_j = get_index_in_bloom_filter( bloom_filter_size, sct_i_hashed)

print(index_in_j)

print(f"privately: need to check if index: {index_in_j} of row{rand_row} is 1 or not")

desired_idx = index_in_j
s = keygen()
query = generate_query(desired_idx)

print("Sending the query to the server...")



{'sct_version': 1, 'log_id': 'c2ltcGxlRXhhbXBsZUxvZ0lkSEFTSA==', 'timestamp': 1652934958000, 'extensions': '', 'signature': 'MEYCIQDzKb/5vOM4EQLBqpGaNqhYk1+8rMIz290NX9aZLo/idQIhAJLpSzs25KRO9yYoGvUwDbX5SxVp5DhppXdCN7maF2E3'}
2
privately: need to check if index: 2 of row3 is 1 or not
Sending the query to the server...


In [55]:
# server 

answer = answer_query(query, db)




In [56]:
print("Got the answer back from the server...")


result = decrypt(s, answer)

print("The item at index %d of the database is %d" % (desired_idx, result))

Got the answer back from the server...
The item at index 2 of the database is 1
