# Learning with Errors and Regev Encryption (schemised ) :

Using parameters from the paper: **One server for the price of Two: Simple and Fast Single-Server Private Information Retreival**

Here the number of LWE samples(m) = m

In [83]:
import numpy as np


# parameters
n = 2**10
m = 5 # sqrt(N), number of samples

error_values = {
    "loc": 0,
    "sigma": 6.4,
}
q = 2**23
p = 991 # plaintext modulus
scaling_factor = np.floor(q/p)
# x = np.random.choice([i for i in range(0, p+1)], m)
x = np.random.choice([i for i in range(0, 2)], m)

# x = np.array([0, 1])

print(f"scaling_factor = floor(q/p) = {np.floor(q/p)}")
print(f"x = {x}")


scaling_factor = floor(q/p) = 8464.0
x = [1 1 0 0 1]


In [84]:
#using matrices (when you have m samples)


def sampleLWE(m,n,q,error_values, s):
    A= np.random.randint(0, q, (m,n))
    
    e= np.random.normal(error_values["loc"], error_values["sigma"], (m) )

    print(f"A = {A}")
    print(f"s = {s}")
    # print(f"e = {e}")


    # Computing the dot product and adding the error

    # Outputting the vectors a, s and the value b

    b = (np.dot(A,s)  + e ) % q
    print(f"b = As + e mod q = {b}")
    # b_prime = (np.dot(A,s) % q + e) % q


    return A, b




In [85]:
# print(f"A = ", A)
# print(type(A), A.shape)
# print(f"s = ", s)
# print(type(s), s.shape)
# print(f"e = ", e)
# print(type(e), e.shape)

In [86]:
secret= np.random.randint(0, q, (n))

A, b = sampleLWE(m,n,q,error_values, secret)

A = [[4428230 7580202 1337775 ... 1151746 5475397 6814858]
 [  67830 2879900 2240218 ... 2795930 1600277   34347]
 [8291932 8053719 2120747 ... 5299398 7248522  446158]
 [6871035 1793663  775303 ... 3533582 7610383  208551]
 [3575757 1541482 5613685 ... 2241445 4040905  324064]]
s = [7484635 2924951 4359309 ... 5362632 8021733 3816114]
b = As + e mod q = [3266240. 2629876. 3957420. 7038000. 3786464.]


In [87]:
# print(f"as mod q = {np.dot(A, s)% q}")

# print(f"(b = As mod q + e ) mod q = ", b)

# print(f" b_prime = As + e mod q    = {b_prime}")

In [88]:
# Encryption

def regevEncrypt(b, x, p, q):
    scaling_factor = np.floor(q/p)
    c =( b + scaling_factor*x ) 
    c_mod_q = c % q

    

    # print(f"c= As + e + (floor(q/p) * x) \n \\ \
    # = As + e + {scaling_factor}*{x} = {c} = {c_mod_q}")

    return c_mod_q

In [89]:
c = regevEncrypt(b, x, p, q)

print(c)

[3274704. 2638340. 3957420. 7038000. 3794928.]


In [90]:
#Decryption

# print(np.dot(a, s), np.dot(a,s) % q)

def rounding(x, round_off_to):
    """
    Rounds off a number x to the nearest multiple of round_off_to.

    :param x: The number to be rounded off.
    :param round_off_to: The nearest multiple to which x needs to be rounded off.
    :return: The rounded off value.
    """
    return np.round(x / round_off_to) * round_off_to

def regevDecrpt(A, s, q, p, c):
    scaling_factor = np.floor(q/p)
    # a_s_mod_q = np.dot(A,s)%q 
    # print(f"a_s_modq = as mod q = ", a_s_mod_q)

    d_hat = (c - np.dot(A, s)) % q 

    print(f"d_hat = c - as mod q= {c} - {np.dot(A,s)} mod q = ", d_hat)
    rounded_d = rounding(d_hat, scaling_factor)



    print(f"rounded d = {rounded_d}")
    
    d = rounded_d / scaling_factor
    print(f"d = rounded_d/ floor(q/p)= {rounded_d}/ {scaling_factor} = {d}" )
    return d 






In [91]:
print(f"x = {x}")
d = regevDecrpt(A, secret, q, p, c)

x = [1 1 0 0 1]
d_hat = c - as mod q= [3274704. 2638340. 3957420. 7038000. 3794928.] - [19598550466942654 18183143087939836 18886024234820269 18270003319759930
 19059480809031384] mod q =  [   8464.    8456.       0. 8388600.    8472.]
rounded d = [   8464.    8464.       0. 8387824.    8464.]
d = rounded_d/ floor(q/p)= [   8464.    8464.       0. 8387824.    8464.]/ 8464.0 = [  1.   1.   0. 991.   1.]
