# Learning with Errors and Regev Encryption(m bits) Example:

Using parameters from the paper: **One server for the price of Two: Simple and Fast Single-Server Private Information Retreival**

Here the number of LWE samples(m) = m

In [38]:
import numpy as np


# parameters
n = 2**10
m = 2 # sqrt(N), number of samples

error_values = {
    "loc": 0,
    "sigma": 6.4,
}
q = 2**23
p = 991 # plaintext modulus
scaling_factor = np.floor(q/p)
x = np.random.choice([i for i in range(0, p+1)], m)

print(f"scaling_factor = floor(q/p) = {np.floor(q/p)}")
print(f"x = {x}")


scaling_factor = floor(q/p) = 8464.0
x = [ 63 147]


In [39]:
#using matrices (when you have m samples)

A= np.random.randint(0, q, (m,n))
s= np.random.randint(0, q, (n))
e= np.random.normal(error_values["loc"], error_values["sigma"], (m) )

print(f"A = {A}")
print(f"s = {s}")
print(f"e = {e}")


A = [[3569817 3643550 4757572 ... 2952728  540034 7586571]
 [3839017 6372961 3189026 ... 7358961 6815881 5944601]]
s = [6181017 2032082 4699636 ... 5701743 1101904 3263150]
e = [ -5.64190836 -11.61768196]


In [40]:
print(f"A = ", A)
print(type(A), A.shape)
print(f"s = ", s)
print(type(s), s.shape)
print(f"e = ", e)
print(type(e), e.shape)

A =  [[3569817 3643550 4757572 ... 2952728  540034 7586571]
 [3839017 6372961 3189026 ... 7358961 6815881 5944601]]
<class 'numpy.ndarray'> (2, 1024)
s =  [6181017 2032082 4699636 ... 5701743 1101904 3263150]
<class 'numpy.ndarray'> (1024,)
e =  [ -5.64190836 -11.61768196]
<class 'numpy.ndarray'> (2,)


In [41]:
# Computing the dot product and adding the error

# Outputting the vectors a, s and the value b

b = (np.dot(A,s)  + e ) % q
# print(f"b = As + e mod q = {b}")
b_prime = (np.dot(A,s) % q + e) % q


In [42]:
print(f"as mod q = {np.dot(A, s)% q}")

print(f"(b = As mod q + e ) mod q = ", b)

print(f" b_prime = As + e mod q    = {b_prime}")

as mod q = [4264606 8086610]
(b = As mod q + e ) mod q =  [4264604. 8086596.]
 b_prime = As + e mod q    = [4264600.35809164 8086598.38231804]


In [43]:
# Encryption

c =( b + scaling_factor*x ) 
c_mod_q = c % q

print(f"q/p= {q}/{p} = {scaling_factor}")

print(f"c= As + e + (floor(q/p) * x) \n \\ \
= {np.dot(A,s) % q} + {e} + {scaling_factor}*{x} = {c} = {c_mod_q}")

q/p= 8388608/991 = 8464.0
c= As + e + (floor(q/p) * x) 
 \ = [4264606 8086610] + [ -5.64190836 -11.61768196] + 8464.0*[ 63 147] = [4797836. 9330804.] = [4797836.  942196.]


In [44]:
#Decryption

# print(np.dot(a, s), np.dot(a,s) % q)

a_s_mod_q = np.dot(A,s)%q 
print(f"a_s_modq = as mod q = ", a_s_mod_q)

d_hat = (c - np.dot(A, s)% q ) 

print(f"d_hat = c - as = {c} - {a_s_mod_q} = ", d_hat)






a_s_modq = as mod q =  [4264606 8086610]
d_hat = c - as = [4797836. 9330804.] - [4264606 8086610] =  [ 533230. 1244194.]


In [45]:
np.round(x/scaling_factor)

array([0., 0.])

In [46]:
def rounding(x, round_off_to):
    """
    Rounds off a number x to the nearest multiple of round_off_to.

    :param x: The number to be rounded off.
    :param round_off_to: The nearest multiple to which x needs to be rounded off.
    :return: The rounded off value.
    """
    return np.round(x / round_off_to) * round_off_to

rounded_d = rounding(d_hat, scaling_factor)



print(f"rounded d = {rounded_d}")

rounded d = [ 533232. 1244208.]


In [47]:
# rounding to the nearest multiple of q/2
#manualy rounding off 33283 to 33280


# print(f" c - as rounded = ", dec)
# print(f"floor q/2= ", np.floor(q/2))
print(f"x = {x}")
d = rounded_d / scaling_factor
print(f"d = rounded_d/ floor(q/p)= {rounded_d}/ {scaling_factor} = {d}" )
# print(f"rounded dec" , dec)
# dec = (c - np.dot(a, s) ) % q 

x = [ 63 147]
d = rounded_d/ floor(q/p)= [ 533232. 1244208.]/ 8464.0 = [ 63. 147.]
