# Learning with Errors and Regev Encryption (schemised ) :

Using parameters from the paper: **One server for the price of Two: Simple and Fast Single-Server Private Information Retreival**

Here the number of LWE samples(m) = m

In [206]:
import numpy as np


# parameters
n = 2**10
m = 5 # sqrt(N), number of samples

error_values = {
    "loc": 0,
    "sigma": 6.4,
}
q = 2**23
p = 991 # plaintext modulus
scaling_factor = np.floor(q/p)
# x = np.random.choice([i for i in range(0, p+1)], m)
x = np.random.choice([i for i in range(0, 2)], m)

# x = np.array([0, 1])

print(f"scaling_factor = floor(q/p) = {np.floor(q/p)}")
print(f"x = {x}")


scaling_factor = floor(q/p) = 8464.0
x = [0 1 1 1 1]


In [207]:
#using matrices (when you have m samples)


def sampleLWE(m,n,q,error_values, s):
    A= np.random.randint(0, q, (m,n))
    
    e= np.random.normal(error_values["loc"], error_values["sigma"], (m) )

    print(f"A = {A}")
    print(f"s = {s}")
    # print(f"e = {e}")


    # Computing the dot product and adding the error

    # Outputting the vectors a, s and the value b

    b = (np.dot(A,s)  + e ) % q
    print(f"b = As + e mod q = {b}")
    # b_prime = (np.dot(A,s) % q + e) % q


    return A, b




In [208]:
# print(f"A = ", A)
# print(type(A), A.shape)
# print(f"s = ", s)
# print(type(s), s.shape)
# print(f"e = ", e)
# print(type(e), e.shape)

In [209]:
secret= np.random.randint(0, q, (n))

A, b = sampleLWE(m,n,q,error_values, secret)

A = [[7740959 7510635 4821461 ...  804511 1743265 4614555]
 [8035919 6835257 8163988 ... 3747462 4251725 7104997]
 [ 318183 8136235 8029781 ... 6789019 1423095 4905566]
 [6059292 1255307 7643236 ... 2969990  186613 7274419]
 [6532922 5027432 7200979 ... 3986819 6332233  894938]]
s = [6431333 7484368 5713869 ... 1662153 2739012 8343249]
b = As + e mod q = [ 765864. 3028438. 2525834. 8222930. 1724640.]


In [210]:
# print(f"as mod q = {np.dot(A, s)% q}")

# print(f"(b = As mod q + e ) mod q = ", b)

# print(f" b_prime = As + e mod q    = {b_prime}")

In [211]:
# Encryption

def regevEncrypt(b, x, p, q):
    scaling_factor = np.floor(q/p)
    c =( b + scaling_factor*x ) 
    c_mod_q = c % q

    

    # print(f"c= As + e + (floor(q/p) * x) \n \\ \
    # = As + e + {scaling_factor}*{x} = {c} = {c_mod_q}")

    return c_mod_q

In [212]:
c = regevEncrypt(b, x, p, q)

print(c)

[ 765864. 3036902. 2534298. 8231394. 1733104.]


In [213]:
#Decryption

# print(np.dot(a, s), np.dot(a,s) % q)

def rounding(x, round_off_to):
    """
    Rounds off a number x to the nearest multiple of round_off_to.

    :param x: The number to be rounded off.
    :param round_off_to: The nearest multiple to which x needs to be rounded off.
    :return: The rounded off value.
    """
    return np.round(x / round_off_to) * round_off_to

def regevDecrpt(A, s, q, p, c):
    scaling_factor = np.floor(q/p)
    # a_s_mod_q = np.dot(A,s)%q 
    # print(f"a_s_modq = as mod q = ", a_s_mod_q)

    d_hat = (c - np.dot(A, s)) % q 

    print(f"d_hat = c - as mod q= {c} - {np.dot(A,s)} mod q = ", d_hat)
    rounded_d = rounding(d_hat, scaling_factor)



    print(f"rounded d = {rounded_d}")
    
    d = rounded_d / scaling_factor
    # print(f"d = rounded_d/ floor(q/p)= {rounded_d}/ {scaling_factor} = {d}" )
    # for i in range(d.shape[0]):
    #     if d[i] == 991:
    #         d[i]=0
    return d 






In [214]:
print(f"x = {x}")
d = regevDecrpt(A, secret, q, p, c)
print(d)

x = [0 1 1 1 1]
d_hat = c - as mod q= [ 765864. 3036902. 2534298. 8231394. 1733104.] - [17384834998185899 17678359944115671 17906791990332044 17354156431734996
 17486127734345964] mod q =  [8388604.    8462.    8462.    8462.    8452.]
rounded d = [8387824.    8464.    8464.    8464.    8464.]
[0. 1. 1. 1. 1.]


In [215]:
print(d)
print(type(d))
print(d[2])

d[2]== 991

d.shape[0]

for i in range(d.shape[0]):
    if d[i] == 991:
        d[i]=0
    
print(d)

[0. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1.0
[0. 1. 1. 1. 1.]
