# populate the bloom filter  
  
Read one SCT from file
serialise it
hash it
put it in bloom filer

In [15]:
# read SCTs


import json

# read SCTS from a JSON encoded file
# Path to the JSON file
file_path = 'Example_SCTs.json'

# Read the JSON data from the file
with open(file_path, 'r') as file:
    sct_list = json.load(file)

# Output the loaded data to verify
print(len(sct_list))
print(type(sct_list[0]))
print(sct_list[0])



3
<class 'dict'>
{'sct_version': 1, 'log_id': 'VWhJdXZrS0pIUFFrUk5ER2JDaWU=', 'timestamp': 1652934758000, 'extensions': '', 'signature': 'MEUCIQDqZIjuNXmV+Rm9dl7h4/u+vZG3+Yj5CISgAzimuths/aiEQIgNupUwGiW8QHfy7WqIuYGCuR+cPkryBJcRqRHTLFa4='}


In [16]:
# testing out functionality

# import json
# import hashlib


# # Serialize the SCT1 data into a JSON string
# sct1_serialized = json.dumps(sct_list[0])

# # Define a salt (this should be kept secure and used consistently if needed for verification later)
# salt = b'my_secure_salt'

# # Create a SHA256 hash object and update it with the salt and the serialized data
# hash_obj = hashlib.sha256()
# hash_obj.update(salt)  # Update with the salt
# hash_obj.update(sct1_serialized.encode())  # Update with the serialized SCT1 data

# # Get the hexadecimal representation of the hash
# sct1_hashed = hash_obj.hexdigest()

# # Output the hashed SCT1
# print(sct1_hashed)


In [17]:
#functionised

import json
import hashlib

def serialise_and_hash(salt, sct):
    """salt : <class 'bytes'>
        sct : <class 'dict'>

        return: <class 'str'>
    """
    # Serialize the SCT1 data into a JSON string
    sct_serialized = json.dumps(sct)

    # Define a salt (this should be kept secure and used consistently if needed for verification later)
    # salt = b'my_secure_salt'

    # Create a SHA256 hash object and update it with the salt and the serialized data
    hash_obj = hashlib.sha256()
    hash_obj.update(salt)  # Update with the salt
    hash_obj.update(sct_serialized.encode())  # Update with the serialized SCT1 data

    # Get the hexadecimal representation of the hash
    sct_hashed = hash_obj.hexdigest()

    # Output the hashed SCT1
    return sct_hashed


# Define a salt (this should be kept secure and used consistently if needed for verification later)
salt = b'my_secure_salt'
sct1_hashed = serialise_and_hash( salt, sct_list[0])
print(sct1_hashed)
print(type(sct1_hashed))

efd1b0ab32452c7e0afe1e42df065cc597ccb11a646e24ee767d97ffd13e1359
<class 'str'>


In [18]:
import hashlib

# Define the Bloom filter size
bloom_filter_size = 5  # Smaller size for demonstration
bloom_filter = [0] * bloom_filter_size  # Initialize the Bloom filter with zeros

# Example SHA-256 hash (as if computed from serialized SCT1 with a salt)
# sct1_hashed = 'a3b291cf2bf8eb0e45084af1b2a66554f3a44ed7bfa9b7166eaf0174a5d6d7c7'

# Convert the hash to an index for the Bloom filter
# Typically, the hash is converted to an integer and taken modulo the size of the Bloom filter
hash_as_integer = int(sct1_hashed, 16)  # Convert hex hash to an integer
index = hash_as_integer % bloom_filter_size  # Compute index for the Bloom filter

# Update the Bloom filter
bloom_filter[index] = 1  # Set the bit at the index to 1

# Output the entire Bloom filter to confirm the update
bloom_filter


[0, 0, 1, 0, 0]

In [19]:
# Define the Bloom filter size
bloom_filter_size = 5  # Smaller size for demonstration
bloom_filter = [0] * bloom_filter_size  # Initialize the Bloom filter with zeros
no_of_hash_functions = 5

In [20]:
import numpy as np

array1 = np.array(  [[0] * bloom_filter_size] * no_of_hash_functions  )

print(array1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:
print(sct1_hashed)

print(array1[0,1])

efd1b0ab32452c7e0afe1e42df065cc597ccb11a646e24ee767d97ffd13e1359
0


In [22]:

def get_index_in_bloom_filter( bloom_filter_size, hashed_sct):
    # Convert the hash to an index for the Bloom filter

    hash_as_integer = int(hashed_sct, 16)  # Convert hex hash to an integer
    index = hash_as_integer % bloom_filter_size  # Compute index for the Bloom filter

    print(f"index is {index}")
   

    # Output the index
    return index


index = get_index_in_bloom_filter( bloom_filter_size, sct1_hashed)
# Update the Bloom filter
array1[0, index] = 1  # Set the bit at the index to 1



print(array1)

index is 2
[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [23]:
import os

# Generate a random 16-byte salt
random_salt = os.urandom(16)

# Print the generated random salt
print(random_salt)

b'\x8a\xc0F>vs\xa53\xed\x8e\xf5\x94=\xcb\xa3\xed'


In [24]:
salt0 = b'\x02\xa4Yq\xf2u\x87\x90\xa2\r\xeb\xc8\x1d\xb4j\x9f'
salt1 = b'zN\xd9)\x12\xe7\xd61V\x1b\xe55\xa7\xd0\xf2N'
salt2 = b'\x86\x19\x923<\x1egQ\xba\x94\x17^\xaa\xbe\x1b\x0f'
salt3 = b'i\x08\x0f4$3\xe6\xfa\x1e\xc7\xd2\xab\x05"Lg'
salt4 = b'{?(\xbb@*\xb3\xec\x8f\xc5\xea\xf4X4\xe2C'

salt_list= [salt0, salt1, salt2, salt3, salt4]
salt_list= [b'salt0', b'salt1', b'salt2', b'salt3', b'salt4']

bloom_filter_size = 5  # Smaller size for demonstration
bloom_filter_1 = np.array(  [[0] * bloom_filter_size] * no_of_hash_functions  ) # Initialize the Bloom filter with zeros
no_of_hash_functions = bloom_filter_size
print(bloom_filter_1)

# for SCT 0
# for i, sct in enumerate(sct_list):
#     sct0_hashed = serialise_and_hash( salt0, sct_list[0])
#     index = get_index_in_bloom_filter( bloom_filter_size, sct0_hashed)
#     bloom_filter_1[i, index]=1

# print(bloom_filter_1)





[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
for i, sct in enumerate(sct_list):
    print(f"i: {i}, sct: {sct}")
    for j, salt in enumerate(salt_list):
        print(f"j: {j}, salt: {salt}")
        sct_i_hashed = serialise_and_hash( salt, sct)
        index_in_j = get_index_in_bloom_filter( bloom_filter_size, sct_i_hashed)
        print(f"updating element {j}, {index_in_j}")
        bloom_filter_1[j, index_in_j]=1
        print(bloom_filter_1)

print(bloom_filter_1)

i: 0, sct: {'sct_version': 1, 'log_id': 'VWhJdXZrS0pIUFFrUk5ER2JDaWU=', 'timestamp': 1652934758000, 'extensions': '', 'signature': 'MEUCIQDqZIjuNXmV+Rm9dl7h4/u+vZG3+Yj5CISgAzimuths/aiEQIgNupUwGiW8QHfy7WqIuYGCuR+cPkryBJcRqRHTLFa4='}
j: 0, salt: b'salt0'
index is 4
updating element 0, 4
[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
j: 1, salt: b'salt1'
index is 2
updating element 1, 2
[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
j: 2, salt: b'salt2'
index is 1
updating element 2, 1
[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
j: 3, salt: b'salt3'
index is 1
updating element 3, 1
[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]
j: 4, salt: b'salt4'
index is 0
updating element 4, 0
[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]
i: 1, sct: {'sct_version': 1, 'log_id': 'dXNlck5hbWVJRFJ1bm5pbmdLZXk=', 'timestamp': 1652934858000, 'extensions': '', 'signature': 'MEQCIF2O7Mr502uViBcN9h7Zv8BpdQWqvmD7

In [33]:
import nbimporter

from regev_encryption_schemised import sampleLWE, regevDecrpt, regevDecrpt


# parameters
# parameters
n = 2**10
m = 5 # sqrt(N), number of samples

error_values = {
    "loc": 0,
    "sigma": 6.4,
}
q = 2**23
p = 991 # plaintext modulus
scaling_factor = np.floor(q/p)
# x = np.random.choice([i for i in range(0, p+1)], m)
x = np.random.choice([i for i in range(0, 2)], m)

# x = np.array([0, 1])

print(f"scaling_factor = floor(q/p) = {np.floor(q/p)}")
print(f"x = {x}")
n = 2**10
m = 5 # sqrt(N), number of samples

error_values = {
    "loc": 0,
    "sigma": 6.4,
}
q = 2**23
p = 991 # plaintext modulus
scaling_factor = np.floor(q/p)
# x = np.random.choice([i for i in range(0, p+1)], m)
x = np.random.choice([i for i in range(0, 2)], m)

# x = np.array([0, 1])

print(f"scaling_factor = floor(q/p) = {np.floor(q/p)}")
print(f"x = {x}")

secret= np.random.randint(0, q, (n))

A, b = sampleLWE(m,n,q,error_values, secret)


scaling_factor = floor(q/p) = 8464.0
x = [0 0 0 0 0]
scaling_factor = floor(q/p) = 8464.0
x = [0 1 0 1 0]
A = [[2745053 7276149  770881 ... 7505153   73860 6950544]
 [6674315  285887 2728292 ... 7202326 3959185 4666942]
 [3322337 6674171 1588761 ... 5100520 3509777 4294119]
 [1172162 6327670 2933043 ... 5795398 6332193 6787521]
 [7860228 6542746 1327153 ... 7480665 5007077 7644064]]
s = [5609918  143131 1689621 ... 6637703 8270450 4539417]
b = As + e mod q = [5044468. 6369932. 6552814.  426134. 7778646.]


In [34]:
# let the random i <- [A] be 2

x = bloom_filter_1[2]
print(x)

[0 1 1 0 0]


In [36]:

c = regevEncrypt(b, x, p, q)

print(c)

A = [[1218249 1794701 1000387 ... 1168532 4430079  215435]
 [4851225 5736340 6418285 ...  247492 1971583 1274259]
 [4848813 5056466 4608396 ... 2425046 2827506 4795463]
 [5611648 3030796 4694027 ... 3621338 6860016 7879230]
 [2567809 7316424 5272121 ... 6914805 1649860 7547875]]
s = [5609918  143131 1689621 ... 6637703 8270450 4539417]
b = As + e mod q = [3878650. 8032232. 7038456. 4396372. 7198798.]


NameError: name 'regevEncrypt' is not defined

In [ ]:
print(f"x = {x}")
d = regevDecrpt(A, secret, q, p, c)

x = [0 1 1 0 0]


TypeError: regevDecrpt() takes 4 positional arguments but 5 were given