In [3]:
import numpy as np

def random_matrix(n, m, p):
    """Generate a random matrix of size n x m with entries from Z_p."""
    return np.random.randint(0, p, size=(n, m))

def random_vector(n, p):
    """Generate a random row vector of size 1 x n with entries from Z_p."""
    return np.random.randint(0, p, size=(1, n))

def random_noise_vector(n):
    """Generate a noise vector of size 1 x n with entries as 0 or 1."""
    return np.random.randint(0, 2, size=(1, n))  # Values in range [0, 2) i.e., 0 or 1




In [72]:
def sample_true():
    
    A = random_matrix(n, m, p)
    s = random_vector(n, p)
    E = random_noise_vector(m)
    # b = A * s + e
    b = ( np.dot(s, A) % p ) + E
    
    return (A, b)

def sample_random():
    A = random_matrix(n, m, p)
    b = random_vector(m, p)
    
    return (A, b)



print("sample True")

A, b = sample_true()

print("Matrix A:")
print(A)
print("\nNoisy Result:")
print(b)

print("==========================")

print("sample_random")
A, b = sample_random()
print("Matrix A:")
print(A)
print("\nNoisy Result:")
print(b)

sample True
Matrix A:
[[2 0]
 [6 2]
 [0 0]]

Noisy Result:
[[1 1]]
sample_random
Matrix A:
[[3 2]
 [3 6]
 [3 4]]

Noisy Result:
[[3 1]]


In [14]:
n = 512
m = 512
p = 3329

n = 3
m = 2
p = 7

noise_distribution = [-3, 3]

def get_LWE_sample(s):
    A = random_matrix(n,m,p)
    e = random_noise_vector(m)    
    # b = A * s + e
    b = ( np.dot(s, A) % p ) + e   
    return (A, b)


def keygen():
    s = random_vector(n, p)
    return s

def encrypt(s, x):
    assert x == 0 or x == 1 # this is the message
    (A, b) = get_LWE_sample(s)
    c = b + np.floor(p / 2) * x
    return (A, c)

def decrypt(s, A, c):
    # raw = c -A * s
    raw = c - (np.dot(s,A) %p )
    return np.round(raw * 2 / p)

#==================================

s = keygen()
print(f"s: {s}")

# (A, b) = get_LWE_sample(s)
# print(f"b=As+e = {b}\n")     

(A, c) = encrypt(s, x=0)
print(f"A:{A}\n")
print(f"c:{c}\n")

pt = decrypt(s, A, c)
print(f"pt: {pt}")

s: [[1 4 5]]
A:[[6 4]
 [3 1]
 [1 2]]

c:[[3. 5.]]

pt: [[0. 0.]]


s: [[2 4 4]]


NameError: name 'E' is not defined

In [59]:
x =1
assert x == 0 or x == 1